### ISSUE TITLE
Terjadi Error [Wakatime]: Invalid API Key

### ISSUE THREAD

**Issue by luisadha** [Anifyuli/nvim#1]

**Comment by Anifyuli** [comment]
Error ini dikarenakan Anda belum memasukkan Wakatime API. Di konfigurasi ini saya pakai Wakatime untuk tracking kegiatan coding saya, nah untuk panduannya bisa dicek disini [disini](https://wakatime.com/neovim)

**Comment by luisadha** [comment]
Hhmmm. Mungkin aku belum perlu fiturnya jadi aku reinstall neovim lagi. But gara2 nyobain konfig ini jadi terinspirsi pakai warna gruvbox juga
